CREATE DATABASE BD2_TPI_G21
GO

USE BD2_TPI_G21
GO

CREATE TABLE Direccion(
    Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    Calle VARCHAR(33) NOT NULL,
    Altura INT NOT NULL,
    Piso VARCHAR(8) NULL,
    Departamento VARCHAR(10) NULL,
    CodigoPostal VARCHAR(8),
    Localidad VARCHAR(60) NOT NULL,
    Observacion VARCHAR(200) NULL,
)

CREATE TABLE Cliente (
    Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    NroCliente BIGINT NOT NULL,
    Dni VARCHAR(10) NOT NULL,
    Nombre VARCHAR(50) NOT NULL, --HABIA UN NULL DE MAS
    Apellido VARCHAR(50) NOT NULL, -- HABIA UN NULL DE MAS
    Telefono VARCHAR(12) NOT NULL,
    IdDireccion INT NOT NULL,
    Baja BIT NOT NULL DEFAULT 0,
    FOREIGN KEY(IdDireccion) REFERENCES Direccion(Id)
)

CREATE TABLE Usuario (
    Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    Descripcion VARCHAR(50) NOT NULL,
    Usuario VARCHAR(200) NOT NULL,
    Contraseña VARCHAR(80),
    IdCliente INT NOT NULL,
    FOREIGN KEY(IdCliente) REFERENCES Cliente(Id)
)

CREATE TABLE Marca(
    Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    Descripcion VARCHAR(50) NOT NULL,
    Origen VARCHAR(50) NULL,
    UrlImagen VARCHAR(2000) NOT NULL,
)

CREATE TABLE Categorias (
    Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
    Descripcion VARCHAR(80) NOT NULL,
)

CREATE TABLE Proveedor(
Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
RazonSocial Varchar(100) NOT NULL,
Cuit VARCHAR(20) UNIQUE NOT NULL,
Telefono VARCHAR(20) NULL,
IdDireccion INT FOREIGN KEY REFERENCES Direccion(iD),
)

CREATE TABLE Mercaderia(
Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Descripcion VARCHAR(100) NOT NULL,
IdCategorias INT FOREIGN KEY REFERENCES Categorias(Id) NOT NULL,
IdProveedor INT FOREIGN KEY REFERENCES Proveedor(Id) NOT NULL,
IdMarca INT FOREIGN KEY REFERENCES Marca(Id) NOT NULL,
CodMercaderia VARCHAR(50) NOT NULL,
Stock INT NOT NULL,
PrecioUnitario FLOAT NOT NULL,
)

CREATE TABLE MedioPago(
Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Descripcion VARCHAR(50) NOT NULL,
Promocion VARCHAR(100) NULL,
)

CREATE TABLE Compra(
Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
IdMedioPago INT FOREIGN KEY REFERENCES MedioPago(Id),
IdProveedor INT FOREIGN KEY REFERENCES Proveedor(Id),
Fecha DATE NOT NULL DEFAULT GETDATE(),
Total MONEY NOT NULL,
)

CREATE TABLE DetalleCompra(
Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
IdCompra INT FOREIGN KEY REFERENCES Compra(Id) NOT NULL,
IdMercaderia INT FOREIGN KEY REFERENCES Mercaderia(Id) NOT NULL,
PrecioUnitario FLOAT NOT NULL,
Cantidad INT NOT NULL,
Fecha DATE NOT NULL DEFAULT GETDATE()
)

CREATE TABLE Transporte(
Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Descripcion VARCHAR(100) NULL,
PesoMaximo FLOAT NOT NULL,
)

CREATE TABLE Seguimiento (
Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Descripcion VARCHAR(100) NOT NULL,
)

CREATE TABLE Carrito(
Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
IdCliente INT FOREIGN KEY REFERENCES Cliente(Id) NOT NULL,
Estado INT NOT NULL,
Fecha DATE NOT NULL DEFAULT GETDATE(),
)

CREATE TABLE CarritoDetalle(
Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
IdCarrito INT FOREIGN KEY REFERENCES Carrito(Id) NOT NULL,
IdMercaderia INT FOREIGN KEY REFERENCES Mercaderia(Id) NOT NULL,
Cantidad INT NOT NULL,
)

CREATE TABLE Inventario(
    Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    IdMercaderia INT NOT NULL,
    Fecha DATE NOT NULL DEFAULT GETDATE(),
    Stock INT NOT NULL,
    FOREIGN KEY(IdMercaderia) REFERENCES Mercaderia(Id)
)

CREATE TABLE Venta(
    Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    IdCarrito INT NOT NULL,
    IdMedioPago INT NOT NULL,
    Fecha DATE NOT NULL DEFAULT GETDATE(),
    Total MONEY NOT NULL,
    FOREIGN KEY(IdCarrito) REFERENCES Carrito(Id),
    FOREIGN KEY(IdMedioPago) REFERENCES MedioPago(Id)
)

CREATE TABLE DetalleVenta(
    Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    IdVenta INT NOT NULL,
    IdMercaderia INT NOT NULL,
    Cantidad INT NOT NULL,
    PrecioUnitario FLOAT NOT NULL,
    Fecha DATE NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY(IdVenta) REFERENCES Venta(Id),
    FOREIGN KEY(IdMercaderia) REFERENCES Mercaderia(Id)
)

CREATE TABLE RemitoResumen(
    Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    SucRem VARCHAR(50) NOT NULL,
    NroRemito VARCHAR(50) NOT NULL,
    IdTransporte INT NOT NULL,
    Fecha DATE NOT NULL DEFAULT GETDATE(),
    IdVenta INT NOT NULL,
    IdSeguimiento INT NOT NULL,
    FOREIGN KEY(IdTransporte) REFERENCES Transporte(Id),
    FOREIGN KEY(IdVenta) REFERENCES Venta(Id),
    FOREIGN KEY(IdSeguimiento) REFERENCES Seguimiento(Id)
)

CREATE TABLE RemitoDetalle(
    Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    IdRemito INT NOT NULL,
    IdMercaderia INT NOT NULL,
    Cantidad INT NOT NULL,
    FOREIGN KEY(IdRemito) REFERENCES RemitoResumen(Id),
    FOREIGN KEY(IdMercaderia) REFERENCES Mercaderia(Id)
)
GO
