CREATE DATABASE BD2_TPI_G21
GO

USE BD2_TPI_G21
GO

CREATE TABLE Direccion(
    Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    Calle VARCHAR(33) NOT NULL,
    Altura INT NOT NULL,
    Piso VARCHAR(8) NULL,
    Departamento VARCHAR(10) NULL,
    CodigoPostal VARCHAR(8),
    Localidad VARCHAR(60) NOT NULL,
    Observacion VARCHAR(200) NULL,
)

CREATE TABLE Cliente (
    Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    NroCliente BIGINT NOT NULL,
    Dni VARCHAR(10) NOT NULL,
    Nombre VARCHAR(50) NOT NULL, --HABIA UN NULL DE MAS
    Apellido VARCHAR(50) NOT NULL, -- HABIA UN NULL DE MAS
    Telefono VARCHAR(12) NOT NULL,
    IdDireccion INT NOT NULL,
    FOREIGN KEY(IdDireccion) REFERENCES Direccion(Id)
)

CREATE TABLE Usuario (
    Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    Descripcion VARCHAR(50) NOT NULL,
    Usuario VARCHAR(200) NOT NULL,
    Contraseña VARCHAR(80),
    IdCliente INT NOT NULL,
    FOREIGN KEY(IdCliente) REFERENCES Cliente(Id)
)

CREATE TABLE Marca(
    Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    Descripcion VARCHAR(50) NOT NULL,
    Origen VARCHAR(50) NULL,
    UrlImagen VARCHAR(2000) NOT NULL,
)

CREATE TABLE MedioDePago(
    Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    Descripcion VARCHAR(50) NOT NULL,
    Promocion VARCHAR(100) NULL
)

CREATE TABLE Categoria (
    Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
    Descripcion VARCHAR(80) NOT NULL,
)


CREATE TABLE Proveedor(
Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
RazonSocial Varchar(100) NOT NULL,
Cuit VARCHAR(20) UNIQUE NOT NULL,
Telefono VARCHAR(20) NULL,
IdDireccion INT FOREIGN KEY REFERENCES Direccion(iD),
)

CREATE TABLE Mercaderia(
Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Descripcion VARCHAR(100) NOT NULL,
IdCategoria INT FOREIGN KEY REFERENCES Categoria(Id) NOT NULL,
IdProveedor INT FOREIGN KEY REFERENCES Proveedor(Id) NOT NULL,
IdMarca INT FOREIGN KEY REFERENCES Marca(Id) NOT NULL,
CodMercaderia VARCHAR(50) NOT NULL,
Stock INT NOT NULL,
PrecioUnitario FLOAT NOT NULL,
)

CREATE TABLE MedioPago(
Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Descripcion VARCHAR(50) NOT NULL,
Promocion INT NULL,
)

CREATE TABLE Compra(
Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
IdMedioPago INT FOREIGN KEY REFERENCES MedioPago(Id),
IdProveedor INT FOREIGN KEY REFERENCES Proveedor(Id),
Fecha DATE NOT NULL DEFAULT GETDATE(),
Total MONEY NOT NULL,
)

CREATE TABLE DetalleCompra(
Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
IdCompra INT FOREIGN KEY REFERENCES Compra(Id) NOT NULL,
IdMercaderia INT FOREIGN KEY REFERENCES Mercaderia(Id) NOT NULL,
Cantidad INT NOT NULL,
)

CREATE TABLE Transporte(
Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Descripcion VARCHAR(100) NULL,
PesoMaximo FLOAT NOT NULL,
)

CREATE TABLE Seguimiento (
Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Descripcion VARCHAR(100) NOT NULL,
)

CREATE TABLE Carrito(
Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
IdCliente INT FOREIGN KEY REFERENCES Cliente(Id) NOT NULL,
Estado INT NOT NULL,
Fecha DATE NOT NULL DEFAULT GETDATE(),
)

CREATE TABLE CarritoDetalle(
Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
IdCarrito INT FOREIGN KEY REFERENCES Carrito(Id) NOT NULL,
IdMercaderia INT FOREIGN KEY REFERENCES Mercaderia(Id) NOT NULL,
Cantidad INT NOT NULL,
)